Add util functions to the file `bash_funcs`

diff --git a/bash_funcs b/bash_funcs
--- a/bash_funcs
+++ b/bash_funcs
@@ -3,6 +3,11 @@
 # vim: syntax=sh
 # code: language=shellscript
 
+#region util functions
+
+# these functions are generally only used in other functions
+# these kind of functions should have an underscore somewhere in the name
+
 function readlink_portable() {
 	local pathname
 
@@ -66,6 +71,235 @@ function readlink_portable() {
 	fi
 }
 
+function pretty_quote() {
+	#region args
+
+	local str
+
+	case $# in
+		(0)
+			{
+				printf '%s: missing argument: <string>\n' "${FUNCNAME[0]}"
+				printf 'usage: %s <string>\n' "${FUNCNAME[0]}"
+			} >&2
+			return 3
+			;;
+		(1)
+			str="$1"
+			;;
+		(*)
+			{
+				printf '%s: too many arguments: %i\n' "${FUNCNAME[0]}" $(($# - 1))
+				printf 'usage: %s <string>\n' "${FUNCNAME[0]}"
+			} >&2
+			return 4
+			;;
+	esac
+
+	readonly str
+
+	#endregion
+
+	#region quoting string
+
+	local quoted_str
+
+	if [[ "$str" =~ ^[A-Za-z0-9_./:+,-]+$ ]]; then
+		# a string that contains only regular characters that don't need escaping or quoting doesn't need to be quoted
+
+		quoted_str="$str"
+	elif [[ "$str" =~ '!' ]]; then
+		# exclamation marks can't be properly escaped in double quotation marks, which is why we force
+		# single quotation marks in that case
+
+		quoted_str="$str"
+		quoted_str="${quoted_str//\'/\'\\\'\'}" #     'foo!bar'baz'         ->   '\''foo!bar'\''baz'\''
+		quoted_str="'$quoted_str'"              #  '\''foo!bar'\''baz'\''   ->  ''\''foo!bar'\''baz'\'''
+		quoted_str="${quoted_str#\'\'\\\'}"     # ''\''foo!bar'\''baz'\'''  ->      'foo!bar'\''baz'\'''
+		quoted_str="${quoted_str%\\\'\'\'}"     #     'foo!bar'\''baz'\'''  ->      'foo!bar'\''baz'
+	elif [[ ! "$str" =~ \' ]]; then
+		# as long as a string doesn't contain any single quotation marks, it can be quoted very easily by wrapping it
+		# into single quotation marks since they don't support any kind of escape characters
+
+		quoted_str="'$str'"
+	else
+		quoted_str="$str"
+		quoted_str="${quoted_str//\\/\\\\}"
+		quoted_str="${quoted_str//\$/\\\$}"
+		quoted_str="${quoted_str//\"/\\\"}"
+		quoted_str="\"$quoted_str\""
+	fi
+
+	readonly quoted_str
+
+	#endregion
+
+	printf '%s' "$quoted_str"
+
+	if [ -t 1 ]; then
+		printf '\n'
+	fi
+}
+complete pretty_quote
+
+function is_color_supported() {
+	#region args
+
+	local fd || return
+
+	case $# in
+		(0)
+			{
+				printf '%s: missing argument: <fd>\n' "${FUNCNAME[0]}"
+				printf 'usage: %s <fd>\n' "${FUNCNAME[0]}"
+			} >&2
+			return 3
+			;;
+		(1)
+			if [ -z "$1" ]; then
+				printf '%s: argument must not be empty\n' "${FUNCNAME[0]}" >&2
+				return 9
+			fi
+
+			fd="$1" || return
+			;;
+		(*)
+			{
+				printf '%s: too many arguments: %i\n' "${FUNCNAME[0]}" $(($# - 1))
+				printf 'usage: %s <fd>\n' "${FUNCNAME[0]}"
+			} >&2
+			return 4
+			;;
+	esac
+
+	readonly fd || return
+
+	#endregion
+
+	if [ -n "${NO_COLOR-}" ] || [ ! -t "$fd" ] || ! command -v tput > '/dev/null'; then
+		return 32
+	fi
+
+	case "$TERM" in
+		('xterm-color'|*'-256color'|'xterm-kitty')
+			return 0
+			;;
+	esac
+
+	if tput 'setaf' '1' >& '/dev/null'; then
+		# We have color support; assume it's compliant with Ecma-48 (ISO/IEC-6429).
+		# Lack of such support is extremely rare, and such a case would tend to support setf rather than setaf.)
+		return 0
+	else
+		return 32
+	fi
+}
+complete is_color_supported
+
+function trace_cmd() {
+	if (($# == 0)); then
+		{
+			printf '%s: missing arguments: <args>...\n' "${FUNCNAME[0]}"
+			printf 'usage: %s [--dry-run] <args>...\n' "${FUNCNAME[0]}"
+		} >&2
+		return 3
+	fi
+
+	#region dry run
+
+	local dry_run || return
+	dry_run=false || return
+
+	if [ "$1" = '--dry-run' ]; then
+		dry_run=true || return
+
+		shift 1 || return
+	fi
+
+	case "${TRACE_CMD_DRY_RUN-}" in
+		(['yY']*)
+			dry_run=true || return
+			;;
+	esac
+
+	readonly dry_run || return
+
+	#endregion
+
+	#region building pretty args
+
+	local -a pretty_args || return
+	pretty_args=() || return
+
+	local arg || return
+	for arg in "$@"; do
+		local pretty_arg || return
+		pretty_arg="$(pretty_quote "$arg" && printf x)" || return
+		pretty_arg="${pretty_arg%x}" || return
+
+		pretty_args+=("$pretty_arg") || return
+
+		unset -v pretty_arg || return
+	done
+	unset -v arg || return
+
+	readonly pretty_args || return
+
+	#endregion
+
+	#region checking for color support
+
+	local color_supported || return
+	color_supported=false || return
+
+	if is_color_supported 2; then
+		color_supported=true || return
+	fi
+
+	readonly color_supported || return
+
+	#endregion
+
+	if $color_supported; then
+		{ tput bold && tput setaf 4; } >&2 || return
+	fi
+
+	{
+		printf '$' || return
+		printf ' %s' "${pretty_args[@]}" || return
+	} >&2
+
+	if $color_supported; then
+		tput sgr0 >&2 || return
+	fi
+
+	printf '\n' >&2 || return
+
+	if ! $dry_run; then
+		"$@"
+	fi
+}
+complete -F _command trace_cmd
+
+function try_as_root() {
+	if command -v doas > '/dev/null'; then
+		doas "$@"
+		return
+	fi
+
+	if command -v sudo > '/dev/null'; then
+		sudo "$@"
+		return
+	fi
+
+	"$@"
+}
+complete -F _command try_as_root
+
+#endregion
+
+#region sourcing other functions
+
 declare __dotfiles_bash_funcs__sourced_file_pathname
 __dotfiles_bash_funcs__sourced_file_pathname="${BASH_SOURCE[0]}"
 
@@ -106,3 +340,5 @@ unset -v __dotfiles_bash_funcs__bash_func_file_pathname
 
 unset -v __dotfiles_bash_funcs__dotfiles_dir_pathname \
          __dotfiles_bash_funcs__sourced_file_pathname
+
+#endregion
